# Generated by Django 4.2.16 on 2025-10-27 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('service_type', models.CharField(choices=[('local', 'Local Move'), ('interstate', 'Interstate Move'), ('international', 'International Move'), ('storage', 'Storage Service'), ('packing', 'Packing Service'), ('cleaning', 'Cleaning Service'), ('other', 'Other Service')], default='local', max_length=20, verbose_name='Service type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (AUD)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Service date')),
                ('payment_method', models.CharField(choices=[('CARD', 'Credit/Debit Card'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('EFTPOS', 'EFTPOS'), ('PAYPAL', 'PayPal'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=15, verbose_name='Payment method')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='Client name')),
                ('pickup_address', models.TextField(blank=True, verbose_name='Pickup address')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Delivery address')),
                ('description', models.TextField(blank=True, verbose_name='Service description')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Reference number')),
                ('accounting_year', models.PositiveIntegerField(db_index=True, verbose_name='Accounting year')),
                ('accounting_month', models.PositiveSmallIntegerField(db_index=True, verbose_name='Accounting month')),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Incomes',
                'db_table': 'incomes',
                'ordering': ['-date', '-created'],
                'indexes': [models.Index(fields=['date'], name='incomes_date_2e1bcd_idx'), models.Index(fields=['accounting_year', 'accounting_month'], name='incomes_account_8bd99d_idx'), models.Index(fields=['service_type', 'date'], name='incomes_service_32b24b_idx')],
            },
        ),
    ]
