# Generated by Django 4.2.16 on 2025-10-26 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('name', models.CharField(max_length=255, verbose_name='Business line name')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL slug')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='Level')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('location', models.CharField(blank=True, help_text='e.g. East Perth, West Perth, Fremantle', max_length=255, verbose_name='Service location')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='business_lines.businessline', verbose_name='Parent business line')),
            ],
            options={
                'verbose_name': 'Business line',
                'verbose_name_plural': 'Business lines',
                'db_table': 'business_lines',
                'ordering': ['level', 'order', 'name'],
                'indexes': [models.Index(fields=['parent', 'level'], name='business_li_parent__301d3f_idx'), models.Index(fields=['is_active', 'level'], name='business_li_is_acti_f555fe_idx'), models.Index(fields=['slug'], name='business_li_slug_ce5a1c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='businessline',
            constraint=models.CheckConstraint(check=models.Q(('level__gte', 1), ('level__lte', 3)), name='business_line_level_range'),
        ),
        migrations.AlterUniqueTogether(
            name='businessline',
            unique_together={('slug', 'parent'), ('name', 'parent')},
        ),
    ]
