#!/usr/bin/env bash
# =============================================================================
# Script to configure DNS on Hetzner (or any provider)
# DNS setup guide for westforceremovals.com
# =============================================================================

echo "=============================================="
echo "  DNS CONFIGURATION - WESTFORCE REMOVALS"
echo "=============================================="
echo ""
echo "Set up the following DNS records in your domain provider:"
echo ""
echo "If your Hetzner server IP is: \$SERVER_IP"
echo ""
echo "┌─────────┬──────────────────────┬─────────────────┬─────────┐"
echo "│  Type   │       Name           │      Value      │   TTL   │"
echo "├─────────┼──────────────────────┼─────────────────┼─────────┤"
echo "│    A    │          @           │   \$SERVER_IP   │  3600   │"
echo "│    A    │         www          │   \$SERVER_IP   │  3600   │"
echo "│  AAAA   │          @           │   \$SERVER_IPv6 │  3600   │"
echo "│  AAAA   │         www          │   \$SERVER_IPv6 │  3600   │"
echo "└─────────┴──────────────────────┴─────────────────┴─────────┘"
echo ""
echo "Additional recommended records for email:"
echo ""
echo "┌─────────┬──────────────────────┬─────────────────────────────────────────┐"
echo "│  Type   │       Name           │                 Value                   │"
echo "├─────────┼──────────────────────┼─────────────────────────────────────────┤"
echo "│   MX    │          @           │   Depends on your email provider        │"
echo "│   TXT   │          @           │   v=spf1 include:_spf.your-provider ~all │"
echo "│   TXT   │     _dmarc           │   v=DMARC1; p=quarantine; ...           │"
echo "└─────────┴──────────────────────┴─────────────────────────────────────────┘"
echo ""
echo "=============================================="
echo "  DNS VERIFICATION"
echo "=============================================="
echo ""
echo "After setting up the DNS, verify with these commands:"
echo ""
echo "  # Verify A record"
echo "  dig +short westforceremovals.com A"
echo ""
echo "  # Verify AAAA record (IPv6)"
echo "  dig +short westforceremovals.com AAAA"
echo ""
echo "  # Verify global propagation"
echo "  # Visit: https://www.whatsmydns.net/#A/westforceremovals.com"
echo ""
echo "⚠️  IMPORTANT: DNS propagation can take up to 48 hours,"
echo "    although it is usually much faster (minutes to a few hours)."
echo ""
