# Generated by Django 4.2.16 on 2025-10-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='gst_rate',
        ),
    ]
