# Generated by Django 4.2.16 on 2025-10-27 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial_expenses_system'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_service_7fd0d9_idx',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='service_category',
        ),
    ]
