# Generated by Django 4.2.16 on 2025-10-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial_authentication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Manager User', 'verbose_name_plural': 'Manager Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(default='Westforce Moving Company', max_length=200, verbose_name='Company name'),
        ),
    ]
